ENC_MAP = {
    #Minusculas
    'a':	'Q1fz',
    'b':	'K8rt',
    'c':	'M3pl',
    'd':	'Z7ax',
    'e':	'B9ty',
    'f':	'W4cs',
    'g':	'J2km',
    'h':	'R5vn',
    'i':	'P6qd',
    'j':	'S3hb',
    'k':	'D8kz',
    'l':	'F2lm',
    'm':	'H7mw',
    'n':    'L9nt',
    'ñ':	'q4ñZ',
    'o':	'C4ov',
    'p':	'V5pr',
    'q':	'T3qx',
    'r':	'X6rb',
    's':	'G1sy',
    't':	'N8tk',
    'u':	'Y2uo',
    'v':	'E7vw',
    'w':	'U3wh',
    'x':	'O6xj',
    'y':	'I4yp',
    'z':	'A5zq',
    #-Minusculas-

    #Mayusculas
        'A': 'q7LM',
    'B': 'k2RP',
    'C': 'm9HT',
    'D': 'z4NV',
    'E': 'b1QK',
    'F': 'w8JG',
    'G': 'j6SZ',
    'H': 'r3XF',
    'I': 'p5DW',
    'J': 's2VB',
    'K': 'd7CZ',
    'L': 'f4MQ',
    'M': 'h1LR',
    'N': 'l8PY',
    'Ñ': 'MÑ7p',
    'O': 'c6TW',
    'P': 'v3HB',
    'Q': 't9KG',
    'R': 'x5JR',
    'S': 'g2MN',
    'T': 'n7QS',
    'U': 'y4PT',
    'V': 'e1RW',
    'W': 'u9CL',
    'X': 'o6FV',
    'Y': 'i3GY',
    'Z': 'a8ZX',
    #-Mayusculas-

    # Números
    '0': '@4$f',
    '1': '%8#k',
    '2': '&1!v',
    '3': '*9?c',
    '4': '^2@h',
    '5': '~7&x',
    '6': '+5$m',
    '7': '=3!p',
    '8': '$6^t',
    '9': '#0*q',
    #-Numeros-

    # Espacio , tab y salto de linea
    ' ': '__s!',
    '\t': 't_b@',
    '\n': 'Ln#4',
    # Símbolos
    '¿': 'odJF',
    '?': 'Crn*',
    '¡': 'l2ed',
    '!': 'lBD#',
    '"': 'd-z*',
    '#': '1C5J',
    '$': 'au2R',
    '%': 'JtBR',
    '&': 'nlWm',
    '/': 'TSHf',
    '(': '6&pW',
    ')': 'k_LU',
    '=': 'yifD',
    '\'': 'LkDm',
    '+': 'WJ6U',
    '-': 'uVTA',
    '_': 'Ijv&',
    '*': 'Fu7W',
    '\\': 'I-CP',
    '@': 'hDeO',
    '>': 'ZIiB',
    '<': '?OB@',
    '{': 'Y6sH',
    '}': 'rF-&',
    'ç': 'H2ZU',
    '[': 'Cr$@',
    ']': 'lgot',
    '^': 'u2iX',
    ',': 'W7^G',
    ';': '_bo&',
    ':': 'IRoL',
    '.': '3u6a',
    '|': 'vR4~',
    '~': 'Qm9|',
    #-Simbolos
}

# Diccionario inverso para desencriptar
DEC_MAP = {code: char for char, code in ENC_MAP.items()}